--------------------------------------------------------
-- Archivo creado  - jueves-septiembre-26-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_TBL_ACTIVIDAD
--------------------------------------------------------

   CREATE SEQUENCE  "BDS_ESCOM"."SEQ_TBL_ACTIVIDAD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TBL_BITACORA
--------------------------------------------------------

   CREATE SEQUENCE  "BDS_ESCOM"."SEQ_TBL_BITACORA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TBL_CONFIGURACION
--------------------------------------------------------

   CREATE SEQUENCE  "BDS_ESCOM"."SEQ_TBL_CONFIGURACION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TBL_MODULO
--------------------------------------------------------

   CREATE SEQUENCE  "BDS_ESCOM"."SEQ_TBL_MODULO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TBL_TIPODOCUMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "BDS_ESCOM"."SEQ_TBL_TIPODOCUMENTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TBL_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "BDS_ESCOM"."SEQ_TBL_USUARIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TBL_USUARIOACTIVIDAD
--------------------------------------------------------

   CREATE SEQUENCE  "BDS_ESCOM"."SEQ_TBL_USUARIOACTIVIDAD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table TBL_ACTIVIDAD
--------------------------------------------------------

  CREATE TABLE "BDS_ESCOM"."TBL_ACTIVIDAD" 
   (	"PK_ACT_IDACTIVIDAD" NUMBER, 
	"ACT_ESTADO" VARCHAR2(20 BYTE), 
	"ACT_DESCRIPCIONACTIVIDAD" VARCHAR2(20 BYTE), 
	"ACT_ULTIMAMODIFICACION" DATE, 
	"ACT_NOMBREACTIVIDAD" VARCHAR2(20 BYTE), 
	"FK_ACT_IDMODULO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_BITACORA
--------------------------------------------------------

  CREATE TABLE "BDS_ESCOM"."TBL_BITACORA" 
   (	"PK_BTC_IDBITACORA" NUMBER, 
	"BTC_OPERACION" VARCHAR2(50 BYTE), 
	"FK_BTC_IDUSUARIO" NUMBER, 
	"BTC_TABLAINVOLUCRADA" VARCHAR2(20 BYTE), 
	"BTC_FECHABITACORA" DATE, 
	"BTC_MAC" VARCHAR2(20 BYTE), 
	"FK_BTC_IDMODULO" NUMBER, 
	"BTC_IP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_CONFIGURACION
--------------------------------------------------------

  CREATE TABLE "BDS_ESCOM"."TBL_CONFIGURACION" 
   (	"PK_CONF_IDCONFIGURACION" NUMBER(*,0), 
	"CONF_LOGO" VARCHAR2(50 BYTE), 
	"CONF_IMAGENLOGIN" VARCHAR2(50 BYTE), 
	"CONF_BARRASUPERIOR" VARCHAR2(20 BYTE), 
	"CONF_BARRALATERAL" VARCHAR2(20 BYTE), 
	"CONF_BOTONES" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_MODULO
--------------------------------------------------------

  CREATE TABLE "BDS_ESCOM"."TBL_MODULO" 
   (	"PK_MOD_IDMODULO" NUMBER, 
	"MOD_ULTIMAMODIFICACION" DATE, 
	"MOD_ESTADO" VARCHAR2(20 BYTE), 
	"MOD_IMAGEN" VARCHAR2(100 BYTE), 
	"MOD_NOMBREMODULO" VARCHAR2(20 BYTE), 
	"MOD_DESCRIPCIONMODULO" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPODOCUMENTO
--------------------------------------------------------

  CREATE TABLE "BDS_ESCOM"."TBL_TIPODOCUMENTO" 
   (	"PK_TIP_IDTIPODOCUMENTO" NUMBER, 
	"TIP_TIPODOCUMENTO" VARCHAR2(20 BYTE), 
	"TIP_ULTIMAMODIFICACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_USUARIO
--------------------------------------------------------

  CREATE TABLE "BDS_ESCOM"."TBL_USUARIO" 
   (	"PK_USR_IDUSUARIO" NUMBER, 
	"USR_TOKEN" VARCHAR2(300 BYTE), 
	"USR_NUMERODOCUMENTO" NUMBER, 
	"USR_NUMEROSESIONES" NUMBER, 
	"USR_APELLIDO" VARCHAR2(20 BYTE), 
	"USR_ESTADO" VARCHAR2(20 BYTE), 
	"USR_FECHANACIMIENTO" DATE, 
	"USR_NUMEROINTENTOS" NUMBER, 
	"USR_NOMBRE" VARCHAR2(20 BYTE), 
	"USR_ULTIMAMODIFICACION" DATE, 
	"USR_CORREOELECTRONICO" VARCHAR2(50 BYTE), 
	"FK_USR_IDTIPODOCUMENTO" NUMBER, 
	"USR_CONTRASENA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_USUARIOACTIVIDAD
--------------------------------------------------------

  CREATE TABLE "BDS_ESCOM"."TBL_USUARIOACTIVIDAD" 
   (	"PK_UAC_IDRELACION" NUMBER, 
	"FK_UAC_IDACTIVIDAD" NUMBER, 
	"FK_UAC_IDUSUARIO" NUMBER, 
	"UAC_ULTIMAMODIFICACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BDS_ESCOM.TBL_ACTIVIDAD
SET DEFINE OFF;
Insert into BDS_ESCOM.TBL_ACTIVIDAD (PK_ACT_IDACTIVIDAD,ACT_ESTADO,ACT_DESCRIPCIONACTIVIDAD,ACT_ULTIMAMODIFICACION,ACT_NOMBREACTIVIDAD,FK_ACT_IDMODULO) values ('1','ACTIVA','DESCRIPCION BLA BLA',null,'CREAR USUARIO','1');
Insert into BDS_ESCOM.TBL_ACTIVIDAD (PK_ACT_IDACTIVIDAD,ACT_ESTADO,ACT_DESCRIPCIONACTIVIDAD,ACT_ULTIMAMODIFICACION,ACT_NOMBREACTIVIDAD,FK_ACT_IDMODULO) values ('2','DESACTIVADO','DESACTIVE',to_date('12/12/01','DD/MM/RR'),'BORRAR USUARIO','1');
REM INSERTING into BDS_ESCOM.TBL_BITACORA
SET DEFINE OFF;
Insert into BDS_ESCOM.TBL_BITACORA (PK_BTC_IDBITACORA,BTC_OPERACION,FK_BTC_IDUSUARIO,BTC_TABLAINVOLUCRADA,BTC_FECHABITACORA,BTC_MAC,FK_BTC_IDMODULO,BTC_IP) values ('1','ELIMINAR','1','TBL_MODULO',to_date('12/12/01','DD/MM/RR'),'WSEQ',null,'1211');
Insert into BDS_ESCOM.TBL_BITACORA (PK_BTC_IDBITACORA,BTC_OPERACION,FK_BTC_IDUSUARIO,BTC_TABLAINVOLUCRADA,BTC_FECHABITACORA,BTC_MAC,FK_BTC_IDMODULO,BTC_IP) values ('2','ACTUALIZAR','1','TBL_ACTIVIDAD',to_date('12/12/01','DD/MM/RR'),'2112','1','122');
Insert into BDS_ESCOM.TBL_BITACORA (PK_BTC_IDBITACORA,BTC_OPERACION,FK_BTC_IDUSUARIO,BTC_TABLAINVOLUCRADA,BTC_FECHABITACORA,BTC_MAC,FK_BTC_IDMODULO,BTC_IP) values ('3','INSERT','1','TBL_ACTIVIDAD',to_date('19/07/19','DD/MM/RR'),'xx','1','123');
REM INSERTING into BDS_ESCOM.TBL_CONFIGURACION
SET DEFINE OFF;
REM INSERTING into BDS_ESCOM.TBL_MODULO
SET DEFINE OFF;
Insert into BDS_ESCOM.TBL_MODULO (PK_MOD_IDMODULO,MOD_ULTIMAMODIFICACION,MOD_ESTADO,MOD_IMAGEN,MOD_NOMBREMODULO,MOD_DESCRIPCIONMODULO) values ('1',null,'TRUE','/--//','SUPERADMINISTRADOR','ENCARGADO DE LA SEGURIDAD');
REM INSERTING into BDS_ESCOM.TBL_TIPODOCUMENTO
SET DEFINE OFF;
Insert into BDS_ESCOM.TBL_TIPODOCUMENTO (PK_TIP_IDTIPODOCUMENTO,TIP_TIPODOCUMENTO,TIP_ULTIMAMODIFICACION) values ('1','Cedula',to_date('12/12/00','DD/MM/RR'));
REM INSERTING into BDS_ESCOM.TBL_USUARIO
SET DEFINE OFF;
Insert into BDS_ESCOM.TBL_USUARIO (PK_USR_IDUSUARIO,USR_TOKEN,USR_NUMERODOCUMENTO,USR_NUMEROSESIONES,USR_APELLIDO,USR_ESTADO,USR_FECHANACIMIENTO,USR_NUMEROINTENTOS,USR_NOMBRE,USR_ULTIMAMODIFICACION,USR_CORREOELECTRONICO,FK_USR_IDTIPODOCUMENTO,USR_CONTRASENA) values ('1','QWQ','107983','5','Rodriguez','1',to_date('12/10/98','DD/MM/RR'),'1','Juan',to_date('12/02/90','DD/MM/RR'),'juanperez@gmail.com','1','juan123');
Insert into BDS_ESCOM.TBL_USUARIO (PK_USR_IDUSUARIO,USR_TOKEN,USR_NUMERODOCUMENTO,USR_NUMEROSESIONES,USR_APELLIDO,USR_ESTADO,USR_FECHANACIMIENTO,USR_NUMEROINTENTOS,USR_NOMBRE,USR_ULTIMAMODIFICACION,USR_CORREOELECTRONICO,FK_USR_IDTIPODOCUMENTO,USR_CONTRASENA) values ('2','QWQ','5922','4','Rojas','2',to_date('14/07/00','DD/MM/RR'),'2','Maria',to_date('12/08/00','DD/MM/RR'),'mariarojas@gmail.com','1','maria123');
REM INSERTING into BDS_ESCOM.TBL_USUARIOACTIVIDAD
SET DEFINE OFF;
Insert into BDS_ESCOM.TBL_USUARIOACTIVIDAD (PK_UAC_IDRELACION,FK_UAC_IDACTIVIDAD,FK_UAC_IDUSUARIO,UAC_ULTIMAMODIFICACION) values ('1','1',null,null);
Insert into BDS_ESCOM.TBL_USUARIOACTIVIDAD (PK_UAC_IDRELACION,FK_UAC_IDACTIVIDAD,FK_UAC_IDUSUARIO,UAC_ULTIMAMODIFICACION) values ('2','1',null,null);
--------------------------------------------------------
--  DDL for Index TBL_ACTIVIDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BDS_ESCOM"."TBL_ACTIVIDAD_PK" ON "BDS_ESCOM"."TBL_ACTIVIDAD" ("PK_ACT_IDACTIVIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_BITACORA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BDS_ESCOM"."TBL_BITACORA_PK" ON "BDS_ESCOM"."TBL_BITACORA" ("PK_BTC_IDBITACORA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_CONFIGURACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BDS_ESCOM"."TBL_CONFIGURACION_PK" ON "BDS_ESCOM"."TBL_CONFIGURACION" ("PK_CONF_IDCONFIGURACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_MODULO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BDS_ESCOM"."TBL_MODULO_PK" ON "BDS_ESCOM"."TBL_MODULO" ("PK_MOD_IDMODULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TIPODOCUMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BDS_ESCOM"."TBL_TIPODOCUMENTO_PK" ON "BDS_ESCOM"."TBL_TIPODOCUMENTO" ("PK_TIP_IDTIPODOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_USUARIOACTIVIDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BDS_ESCOM"."TBL_USUARIOACTIVIDAD_PK" ON "BDS_ESCOM"."TBL_USUARIOACTIVIDAD" ("PK_UAC_IDRELACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BDS_ESCOM"."TBL_USUARIO_PK" ON "BDS_ESCOM"."TBL_USUARIO" ("PK_USR_IDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger AUDITORIA_TABLA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BDS_ESCOM"."AUDITORIA_TABLA" 
before insert or update or delete
on TBL_ACTIVIDAD
for each row
begin
if inserting then

insert into      "TBL_BITACORA" (BTC_OPERACION, FK_BTC_IDUSUARIO, BTC_TABLAINVOLUCRADA, BTC_FECHABITACORA, BTC_MAC, FK_BTC_IDMODULO, BTC_IP) values(
'INSERT',
:new.PK_ACT_IDACTIVIDAD,
'TBL_ACTIVIDAD',
sysdate,
'xx',
:new.FK_ACT_IDMODULO,
'123');
end if;
end;

/
ALTER TRIGGER "BDS_ESCOM"."AUDITORIA_TABLA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_SEQ_TBL_ACTIVIDAD
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BDS_ESCOM"."TRIGGER_SEQ_TBL_ACTIVIDAD" 
before insert on TBL_ACTIVIDAD
for each row
begin
    select SEQ_TBL_ACTIVIDAD.nextval into :new.PK_ACT_IDACTIVIDAD from dual;
end;

/
ALTER TRIGGER "BDS_ESCOM"."TRIGGER_SEQ_TBL_ACTIVIDAD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_SEQ_TBL_BITACORA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BDS_ESCOM"."TRIGGER_SEQ_TBL_BITACORA" 
before insert on TBL_BITACORA
for each row
begin
    select SEQ_TBL_BITACORA.nextval into :new.PK_BTC_IDBITACORA from dual;
end;

/
ALTER TRIGGER "BDS_ESCOM"."TRIGGER_SEQ_TBL_BITACORA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_SEQ_TBL_CONFIGURACION
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BDS_ESCOM"."TRIGGER_SEQ_TBL_CONFIGURACION" 
before insert on TBL_CONFIGURACION
for each row
begin
    select SEQ_TBL_CONFIGURACION.nextval into :new.PK_CONF_IDCONFIGURACION from dual;
end;
/
ALTER TRIGGER "BDS_ESCOM"."TRIGGER_SEQ_TBL_CONFIGURACION" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_SEQ_TBL_MODULO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BDS_ESCOM"."TRIGGER_SEQ_TBL_MODULO" 
before insert on TBL_MODULO
for each row
begin
    select SEQ_TBL_MODULO.nextval into :new.PK_MOD_IDMODULO from dual;
end;

/
ALTER TRIGGER "BDS_ESCOM"."TRIGGER_SEQ_TBL_MODULO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_SEQ_TBL_TIPODOCUMENTO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BDS_ESCOM"."TRIGGER_SEQ_TBL_TIPODOCUMENTO" 
before insert on TBL_TIPODOCUMENTO
for each row
begin
    select SEQ_TBL_TIPODOCUMENTO.nextval into :new.PK_TIP_IDTIPODOCUMENTO from dual;
end;

/
ALTER TRIGGER "BDS_ESCOM"."TRIGGER_SEQ_TBL_TIPODOCUMENTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_SEQ_TBL_USUARIO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BDS_ESCOM"."TRIGGER_SEQ_TBL_USUARIO" 
before insert on TBL_USUARIO
for each row
begin
    select SEQ_TBL_USUARIO.nextval into :new.PK_USR_IDUSUARIO from dual;
end;

/
ALTER TRIGGER "BDS_ESCOM"."TRIGGER_SEQ_TBL_USUARIO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_SEQ_TBL_USUARIOACTIVID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BDS_ESCOM"."TRIGGER_SEQ_TBL_USUARIOACTIVID" 
before insert on TBL_USUARIOACTIVIDAD
for each row
begin
    select SEQ_TBL_USUARIOACTIVIDAD.nextval into :new.PK_UAC_IDRELACION from dual;
end;

/
ALTER TRIGGER "BDS_ESCOM"."TRIGGER_SEQ_TBL_USUARIOACTIVID" ENABLE;
--------------------------------------------------------
--  DDL for Function CUSTOM_AUTH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "BDS_ESCOM"."CUSTOM_AUTH" (p_username in VARCHAR2, p_password in VARCHAR2)
return BOOLEAN
is
  l_password varchar2(4000);
  l_stored_password varchar2(4000);
  l_expires_on date;
  l_count number;
begin
-- First, check to see if the user is in the user table
select count(*) into l_count from demo_users where user_name = p_username;
if l_count > 0 then
  -- First, we fetch the stored hashed password & expire date
  select password, expires_on into l_stored_password, l_expires_on
   from demo_users where user_name = p_username;

  -- Next, we check to see if the user's account is expired
  -- If it is, return FALSE
  if l_expires_on > sysdate or l_expires_on is null then

    -- If the account is not expired, we have to apply the custom hash
    -- function to the password
    l_password := custom_hash(p_username, p_password);

    -- Finally, we compare them to see if they are the same and return
    -- either TRUE or FALSE
    if l_password = l_stored_password then
      return true;
    else
      return false;
    end if;
  else
    return false;
  end if;
else
  -- The username provided is not in the DEMO_USERS table
  return false;
end if;
end;


/
--------------------------------------------------------
--  DDL for Function CUSTOM_HASH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "BDS_ESCOM"."CUSTOM_HASH" (p_username in varchar2, p_password in varchar2)
return varchar2
is
  l_password varchar2(4000);
  l_salt varchar2(4000) := '8X14BYL9NHJ0JWHUTTFCYJBOZYP73R';
begin

-- This function should be wrapped, as the hash algorhythm is exposed here.
-- You can change the value of l_salt or the method of which to call the
-- DBMS_OBFUSCATOIN toolkit, but you much reset all of your passwords
-- if you choose to do this.

l_password := utl_raw.cast_to_raw(dbms_obfuscation_toolkit.md5
  (input_string => p_password || substr(l_salt,10,13) || p_username ||
    substr(l_salt, 4,10)));
return l_password;
end;


/
--------------------------------------------------------
--  Constraints for Table TBL_ACTIVIDAD
--------------------------------------------------------

  ALTER TABLE "BDS_ESCOM"."TBL_ACTIVIDAD" MODIFY ("PK_ACT_IDACTIVIDAD" NOT NULL ENABLE);
  ALTER TABLE "BDS_ESCOM"."TBL_ACTIVIDAD" ADD CONSTRAINT "TBL_ACTIVIDAD_PK" PRIMARY KEY ("PK_ACT_IDACTIVIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_BITACORA
--------------------------------------------------------

  ALTER TABLE "BDS_ESCOM"."TBL_BITACORA" MODIFY ("PK_BTC_IDBITACORA" NOT NULL ENABLE);
  ALTER TABLE "BDS_ESCOM"."TBL_BITACORA" ADD CONSTRAINT "TBL_BITACORA_PK" PRIMARY KEY ("PK_BTC_IDBITACORA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CONFIGURACION
--------------------------------------------------------

  ALTER TABLE "BDS_ESCOM"."TBL_CONFIGURACION" ADD CONSTRAINT "TBL_CONFIGURACION_PK" PRIMARY KEY ("PK_CONF_IDCONFIGURACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BDS_ESCOM"."TBL_CONFIGURACION" MODIFY ("PK_CONF_IDCONFIGURACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_MODULO
--------------------------------------------------------

  ALTER TABLE "BDS_ESCOM"."TBL_MODULO" MODIFY ("PK_MOD_IDMODULO" NOT NULL ENABLE);
  ALTER TABLE "BDS_ESCOM"."TBL_MODULO" ADD CONSTRAINT "TBL_MODULO_PK" PRIMARY KEY ("PK_MOD_IDMODULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_TIPODOCUMENTO
--------------------------------------------------------

  ALTER TABLE "BDS_ESCOM"."TBL_TIPODOCUMENTO" MODIFY ("PK_TIP_IDTIPODOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "BDS_ESCOM"."TBL_TIPODOCUMENTO" ADD CONSTRAINT "TBL_TIPODOCUMENTO_PK" PRIMARY KEY ("PK_TIP_IDTIPODOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_USUARIO
--------------------------------------------------------

  ALTER TABLE "BDS_ESCOM"."TBL_USUARIO" MODIFY ("PK_USR_IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "BDS_ESCOM"."TBL_USUARIO" ADD CONSTRAINT "TBL_USUARIO_PK" PRIMARY KEY ("PK_USR_IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_USUARIOACTIVIDAD
--------------------------------------------------------

  ALTER TABLE "BDS_ESCOM"."TBL_USUARIOACTIVIDAD" MODIFY ("PK_UAC_IDRELACION" NOT NULL ENABLE);
  ALTER TABLE "BDS_ESCOM"."TBL_USUARIOACTIVIDAD" ADD CONSTRAINT "TBL_USUARIOACTIVIDAD_PK" PRIMARY KEY ("PK_UAC_IDRELACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_ACTIVIDAD
--------------------------------------------------------

  ALTER TABLE "BDS_ESCOM"."TBL_ACTIVIDAD" ADD CONSTRAINT "RELACION_IDMODULO" FOREIGN KEY ("FK_ACT_IDMODULO")
	  REFERENCES "BDS_ESCOM"."TBL_MODULO" ("PK_MOD_IDMODULO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_USUARIO
--------------------------------------------------------

  ALTER TABLE "BDS_ESCOM"."TBL_USUARIO" ADD CONSTRAINT "RELACION_TIPODOC" FOREIGN KEY ("FK_USR_IDTIPODOCUMENTO")
	  REFERENCES "BDS_ESCOM"."TBL_TIPODOCUMENTO" ("PK_TIP_IDTIPODOCUMENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_USUARIOACTIVIDAD
--------------------------------------------------------

  ALTER TABLE "BDS_ESCOM"."TBL_USUARIOACTIVIDAD" ADD CONSTRAINT "RELACION_ACTV" FOREIGN KEY ("FK_UAC_IDACTIVIDAD")
	  REFERENCES "BDS_ESCOM"."TBL_ACTIVIDAD" ("PK_ACT_IDACTIVIDAD") ENABLE;
  ALTER TABLE "BDS_ESCOM"."TBL_USUARIOACTIVIDAD" ADD CONSTRAINT "RELACION_USUARIO" FOREIGN KEY ("FK_UAC_IDUSUARIO")
	  REFERENCES "BDS_ESCOM"."TBL_USUARIO" ("PK_USR_IDUSUARIO") ENABLE;
